### ISSUE TITLE
Video Stream close for no reason

### ISSUE THREAD

**Issue by BrunoC96** [zezo357/flutter_meedu_media_kit#1]
Hi,

Sometime happen that the video stream close by itself with no error or warning and the only log file I have is:

MediaKitEventLoopHandler::Register: std::thread exit: 6223566592
MediaKitEventLoopHandler::Dispose: 6223566592
flutter: media_kit: mpv_terminate_destroy: 6223566592

also other time it closes, but I have those errors, like these:

Opening 'http://live-ipla.pluscdn.pl/t12/18830/0/tv/15520/tv/7958d5f8-1033-49f7-a79d-3a1364ca527f_1390794.ts' for reading
[http @ 0x1275e7600] Cannot reuse HTTP connection for different host: live-ipla-e2-18.pluscdn.pl:-1 != live-ipla.pluscdn.pl:-1
[hls @ 0x1602f65a0] keepalive request failed for 'http://live-ipla.pluscdn.pl/t12/18830/0/tv/15520/tv/5ff27292-81cb-46cb-9417-9d1b7048df22_1390795.ts' with error: 'Invalid argument' when opening url, retrying with new connection
[hls @ 0x1602f65a0] Opening 'http://live-ipla.pluscdn.pl/t12/18830/0/tv/15520/tv/5ff27292-81cb-46cb-9417-9d1b7048df22_1390795.ts' for reading
[hls @ 0x1602f65a0] Skip ('#X-IPLA-LIVE-START: 20230604T082825Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-LIVE-LAST: 20230604T203329Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-SEEKABLE-TO: 20230604T203243Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203243Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203248Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203253Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203258Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203304Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203309Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203314Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203319Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203324Z')
[hls @ 0x1602f65a0] Skip ('#X-IPLA-TIMESTAMP: 20230604T203329Z')
[http @ 0x13c70f740] Cannot reuse HTTP connection for different host: live-ipla-e2-18.pluscdn.pl:-1 != live-ipla.pluscdn.pl:-1
[hls @ 0x1602f65a0] keepalive request failed for 'http://live-ipla.pluscdn.pl/t12/18830/0/tv/15520/tv/4ea799be-6c7a-4a14-b0cb-c4d9603eb732_1390796.ts' with error: 'Invalid argument' when opening url, retrying with new connection
[hls @ 0x1602f65a0] Opening 'http://live-ipla.pluscdn.pl/t12/18830/0/tv/15520/tv/4ea799be-6c7a-4a14-b0cb-c4d9603eb732_1390796.ts' for reading

I don't think they are related to each other, but the behavior is the same, so I'm not sure.

With older version does work fine.

**Comment by abdelaziz-mahdy** [comment]
With what Older version? Media_kit? In that case it's a media_kit related issue not this package, these are only controls wrapper for media_kit video playback

**Comment by abdelaziz-mahdy** [comment]
And I think it's a problem with the host of the network, due to connection being closed

**Comment by BrunoC96** [comment]
Ok, thank you, I open it in media kit.

There is a way to handle the connection lost, with the host?

**Comment by abdelaziz-mahdy** [comment]
> Ok, thank you, I open it in media kit.
> 
> There is a way to handle the connection lost, with the host?

i dont know, the only way i do it is getting a new link

**Comment by BrunoC96** [comment]
Ok, thanks, try to found a solution, to share.
