### ISSUE TITLE
Set Volume or set Mute on network audio Stream

### ISSUE THREAD

**Issue by BrunoC96** [zezo357/flutter_meedu_media_kit#2]
Hi,

I try to set the volume and set mute for my audio stream coming from a network source, but when I try to change the volume, the audio completely cut off and doesn't come back.

This is my audio stream: `"https://radiounoita-live.akamaized.net/hls/live/2032820/radiounoita/radiounoita/radio1_256/chunklist.m3u8"`
I also try with different audio stream, but is the same.

The value for the controller audio are correct, so when I set for example to 0.5 I see from the controller 0.5 and also mute on false, but no audio is reproduced, and I double-check if the controller goes in pause, but it's still going.

**Comment by abdelaziz-mahdy** [comment]
that only happens on audio streams?

**Comment by BrunoC96** [comment]
yes, video works with no problem.

**Comment by abdelaziz-mahdy** [comment]
> yes, video works with no problem.

check again in version `4.2.11`

**Comment by BrunoC96** [comment]
on version `4.2.11` works fine.
