### ISSUE TITLE
Volume.value overflow slider range after controller play or resume

### ISSUE THREAD

**Issue by BrunoC96** [zezo357/flutter_meedu_media_kit#3]
Hi,

So I try recently to use 2 controllers at once, 1 for video and the other one for the audio, because I need video with a different audio played in the background.

So far I use as UI only the video controller, and only initialize the audio one.
For the video controller, I use custom controls (took it from the **example folder** in this repository) to handle every aspect of the status of the player, because I need that audio and video go in sync and if I stop the video also the audio need to stop.

So I use `_meeduPlayerControllerVideo.onPlayerStatusChanged.listen` to handle the `PlayerStatus` changes, completed with a switch statement to handle the 3 condition: pause, playing and complete, where for each i give to the audio controller the option to `pause()` or `play()`.

Now the problem happen when I change the volume and pause and play again the video.
Only if the volume is different to `1.0` or `0.0`, and only after paused and play the video.

When I play again the video, the slider value that is for reference the value of the audio controller `_meeduPlayerControllerAudio.volume.value` is outside the range of the slider or `0.0 <= value <= 1.0`, and it's exactly 100 times the original value of the controller.
So if previously I have 0.695456145615 as my `_meeduPlayerControllerAudio.volume.value` after pausing and play again, this value became 69.5456145615, and the slider overflow.

I solve the problem for play and pause by adding a variable on the `onChanged: (double value)` of the slider that save the slider value when it changes, and use it in the switch statement using a function to override the `100x` time value with this variable.

But now the problem, re-present when I try to set a new data source for the Audio using another stream.
Same problem, so if I have `0.0` or `1.0` as volume no effect, and it set the new Data source with no problem, but if I change the volume and is in between 0.0 and 1.0 the slider have `100x` the real value of the `_meeduPlayerControllerAudio.volume.value` and the widget overflow by 90000 pixel.

**Comment by abdelaziz-mahdy** [comment]
The media_kit volume is 0 to 100 

The original code was optimized 0 to 1 


I will re optimize the code to use volume ranges from 0 to 100


Do you think that will be easy for you to integrate?

Or I optimize all parts of the code to 0 and 1

**Comment by abdelaziz-mahdy** [comment]
can you test on github? it should be fixed

```
  flutter_meedu_media_kit:
    git: 
      url: https://github.com/zezo357/flutter_meedu_media_kit
      path: package/
```

**Comment by BrunoC96** [comment]
I think it is better an optimization because I need to re call a function every time, the control change in some way or another, and the problem is those are the only 2 cases I see, but I think, that it could be occurring in other instance too.

I try the git fix and get you feedback.

**Comment by abdelaziz-mahdy** [comment]
> I think it is better an optimization because I need to re call a function every time, the control change in some way or another, and the problem is those are the only 2 cases I see, but I think, that it could be occurring in other instance too.
> 
> I try the git fix and get you feedback.

test the github one and let me know 

i am keeping the ranges 0 to 1 for now

**Comment by BrunoC96** [comment]
I tested the git repository, and it's working, either when play and pause and when I change the stream.

But I see that when the video player starts the slider value, so the `_meeduPlayerControllerAudio.volume.value` is set to `0.0` but I hear the volume as it is `1.0`.

I also try to force it at the start to go to actually 1.0 but doesn't move.

**Comment by BrunoC96** [comment]
I double-check the `_meeduPlayerControllerAudio.volume.value` it's actually `1.0`, but the slider still starts from `0.0`.

I don't touch the slider value, either the code for the slider, so I think the problem is in the `MeeduPlayerController` when use setting `controlsStyle: ControlsStyle.custom`, but I'm not sure.

**Comment by BrunoC96** [comment]
I also see from the `enabledOverlays: const EnabledOverlays(volume: true)` from the `MeeduPlayerController`, that the overlay of the volume is not `0.0` but `0.01` so I think it's as before a problem with the `media_kit` volume that is from 0 to 100, because is `100x` the value that should be.

**Comment by abdelaziz-mahdy** [comment]
I really don't get the audio and video thing , but I am trying to keep the video_player and media_kit interfaces the same 

In case people want to switch to any of those packages, I don't want migration harder on people



Anyway let me know the problems as points and if you can provide example code that would be a great help to see which problem and if I was able to fix it

**Comment by BrunoC96** [comment]
Solve the issue with last GitHub update.
