### ISSUE TITLE
update dependencies to used wakelock_plus

### ISSUE THREAD

**Issue by Joseph-Nathan** [zezo357/flutter_meedu_media_kit#5]
update dependencies to used wakelock_plus

```
And because every version of flutter_meedu_media_kit depends on wakelock ^0.6.1+2 which depends on wakelock_windows ^0.2.0, wakelock_plus ^1.1.1 is incompatible with flutter_meedu_media_kit.
```

**Comment by abdelaziz-mahdy** [comment]
Thank you for mentioning it, I will do it today hopefully 

If you can provide a pr that will be much appreciated

**Comment by BrunoC96** [comment]
Also for me there is a problem for these decencies, if I can't upgrade media_kit to version above 1.0.2 the screen on android is black so either choose to use directly this library or media_kit.

@zezo357 any update??

**Comment by abdelaziz-mahdy** [comment]
I want to work on it, I just don't have enough time to do it, hopefully I can work on it in the next weekend

**Comment by BrunoC96** [comment]
ok thanks, waiting for update.

**Comment by abdelaziz-mahdy** [comment]
fixed in new release
